on:
    push:
      branches: [test-actions]
      tags:
        - 'v(\d|\.)*'
name: "Publish Release"
jobs:
  publish-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download workflow artifact
          uses: dawidd6/action-download-artifact@v2.27.0
          with:
            workflow: windows.yml
            workflow_conclusion: success

        - name: "Publish Release"
          uses: softprops/action-gh-release@v0.1.15
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: "Cartridges Setup.exe"