on:
    push:
      branches: [test-actions]
      #tags:
      #  - "v\\d.*"
name: Publish Release
jobs:
  publish-release:
      runs-on: ubuntu-latest
      steps:
        - name: Download workflow artifact
          uses: dawidd6/action-download-artifact@v2.27.0
          with:
            workflow: windows.yml
            workflow_conclusion: success

        - name: Checkout
          uses: actions/checkout@v3

        - name: Get release notes
          shell: "python"  
          run: |
            import re, textwrap
            open_file = open("./data/hu.kramo.Cartridges.metainfo.xml.in", "r", encoding="utf-8")
            string = open_file.read()
            open_file.close()
            string = re.findall("<release.*>\s*<description.*>\n([\s\S]*?)\s*</description>\s*<\/release>", string)[0]
            string = textwrap.dedent(string)
            open_file = open("release_notes", "w", encoding="utf-8")
            open_file.write(string)
            open_file.close()

        - name: Publish release
          uses: softprops/action-gh-release@v0.1.15
          with:
            files: "Installer/Cartridges Setup.exe"
            tag_name: ${{ github.ref_name }}
            draft: true
            body_path: "release_notes"