on:
    push:
      branches: [test-actions]
      #tags:
      #  - 'v(\d|\.)*'
name: "Publish Release"
jobs:
  publish-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Download workflow artifact
          uses: dawidd6/action-download-artifact@v2.27.0
          with:
            workflow: windows.yml
            workflow_conclusion: success
        
        - name: "Get tag"
          run: "export git_tag=$(git describe --tags --abbrev=0)"

        - name: "ls"
          run: "ls"

        - name: "Publish Release"
          uses: softprops/action-gh-release@v0.1.15
          with:
            files: "Installer/Cartridges Setup.exe"
            tag_name: ${{ env.tag_name }}
            draft: true
            generate_release_notes: true